language: node_js
install: true

node_js:
  - 0.11

before_install:
  - npm install
  - gem update --system
  - gem install sass --version "=3.2.14"
  - gem install compass --version "=0.12.2"

script:
  - ./node_modules/.bin/gulp build
  - ./node_modules/.bin/gulp eslint

